component: catalogue
service_type: ClusterIP
port: 8080
env: prod
PARAMETERS: "catalogue.prod.MONGO_URL,MONGO_URL catalogue.prod.DOCUMENTDB,DOCUMENTDB"
schema:
  enabled: true
  DB_TYPE: docdb

replicaCount: 2

resources:
  limits:
    cpu: 5000m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi